# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qapi < Formula
  desc "QuantumAPI CLI - Quantum-safe encryption from your terminal"
  homepage "https://quantumapi.eu"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.4/qapi_1.0.4_darwin_amd64.tar.gz"
      sha256 "0158d2d4563e3b5708c5109deda4a0def9169130bbfe5f7ad5304c8dd059a14a"

      def install
        bin.install "qapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.4/qapi_1.0.4_darwin_arm64.tar.gz"
      sha256 "40e0580d928e68d3339cdfe584b8f6bf6506935977ea43ca05ed300ed23fbd10"

      def install
        bin.install "qapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.4/qapi_1.0.4_linux_amd64.tar.gz"
      sha256 "9bee070e41aaa559176c45100a0b013ff3e950fd2c569010a5653fb39176aad1"
      def install
        bin.install "qapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.4/qapi_1.0.4_linux_arm64.tar.gz"
      sha256 "6cc382764e7eab92a484f9547dc7ee52e8d8d1b406d8c636bcadc9ce7e13f50a"
      def install
        bin.install "qapi"
      end
    end
  end

  test do
    system "#{bin}/qapi", "version"
  end
end
