# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qapi < Formula
  desc "QuantumAPI CLI - Quantum-safe encryption from your terminal"
  homepage "https://quantumapi.eu"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.6/qapi_1.0.6_darwin_amd64.tar.gz"
      sha256 "92b1582ee01582b394f3ca9931785a5494a59ae39983112cb819d6cd3055a53e"

      def install
        bin.install "qapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.6/qapi_1.0.6_darwin_arm64.tar.gz"
      sha256 "245d359f4b60936772a5619802356a43e1211ae484d99b7f5a14b13e91f09bc9"

      def install
        bin.install "qapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.6/qapi_1.0.6_linux_amd64.tar.gz"
      sha256 "bbf120be265f8adadda2fa2cebe24ceae9b24f5102a15e2ec68e3d30ff4d89d2"
      def install
        bin.install "qapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/victorZKov/mislata/releases/download/v1.0.6/qapi_1.0.6_linux_arm64.tar.gz"
      sha256 "8af267423fb5e08306d25e514c296f9cdf5418b1baef17cff05946ad01e71eb4"
      def install
        bin.install "qapi"
      end
    end
  end

  test do
    system "#{bin}/qapi", "version"
  end
end
